development:
  adapter: postgresql
  encoding: unicode
  database: GeneralAssembly_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: GeneralAssembly_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: GeneralAssembly_production
  pool: 5

